### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [jappeace/jappeaceApplication#1]
Hi! I am the editor of Haskell Weekly. I would like to be notified when you publish a new post, but as far as I can tell your site (<https://jappieklooster.nl>) does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by jappeace** [comment]
Here it is: https://jappieklooster.nl/atom
You probably want to use category haskell to filter out the other posts

**Comment by tfausak** [comment]
Great, thanks!
