### ISSUE TITLE
Typos and grammar errors in "failing-in-haskell"

### ISSUE THREAD

**Issue by phlummox** [jappeace/jappeaceApplication#2]
Hi,

I noticed some typos and grammatical errors in the "[failing in Haskell][fail-hask]" blog post, which I think distract a reader from the points being made. (I should say, though, that the post is certainly much better English than I could write in Dutch, or indeed in any other language.) Here are the ones I spotted:

[fail-hask]: https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md

- "[Plenty people](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L15)" should probably be "Plenty ***of*** people"
- "[how to achieve above properties](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L43)" should probably be "how to achieve ***the*** above properties"
- "[safes so much debugging time](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L50)" should probably be "***saves*** so much debugging time"
- "[By which we mean in immutable memory computations](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L54)" should probably be "By which we mean immutable memory computations" (no need for "in")
- "[consdired pure](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L78)" should presumably be "***considered*** pure"
- "[one wonders if this could changed](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L79)" should be "one wonders if this could ***be*** changed"
- "[you could factor this out and more typesafe](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L143)" is not grammatical, though I don't know what's intended. "***be*** more type-safe", perhaps?
- "[It's more difficult to recover from an exception then it is](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L160)" should be "It's more difficult to recover from an exception ***than*** it is"
- "[If it's important that an error is handled correctly](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L164)" should be "If it's important that an error ***be*** handled correctly" ("be", here, is in the [present subjunctive][subjunc] mood)
- "[is more preferable](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L210)" should just be "is preferable"
- "[exceptions like above are good](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L211)" seems incorrect, and should probably be something like "exceptions like ***those described*** above are good", or similar
- "[If that's to much work](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L215)" should be "If that's ***too*** much work"
- "[although it's type](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L217)" should be "although ***its*** type"
- "recover ability" ([here](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L34) and [here](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L271)) should be "***recoverability***"
- "[match on string](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L274)" should probably be "match on ***a*** string"
- "[tell what you're talking about to throw](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L367)" is ungrammatical, though I'm not sure exactly what was meant. Perhaps something like "properly describe the context of the error"?

[subjunc]: https://www.merriam-webster.com/words-at-play/getting-in-the-subjunctive-mood

I hope you find these suggestions helpful in improving the post, and making it more accessible to readers.

I see also that you suggest readers "[Let [you] know if [they] disagree, or need help with this](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L424)", but couldn't spot a "comments" section – is there any suggested forum where readers can comment, if they need help or would like to discuss the post further?

**Comment by phlummox** [comment]
One other thing you might want to consider is whether "vague" is exactly the term you're after (for instance, [here](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L32) and [here](https://github.com/jappeace/jappeaceApplication/blob/619113f85155ff627f5f79c02e5e8a1f4d9f766f/content/failing-in-haskell.md?plain=1#L217)).

It's true that in non-technical language, "vague" can be defined as meaning "Of words, language, etc.: Not precise or exact in meaning" [OED]. So one might think that if something isn't *precise*, it must be *vague*. However, in software engineering and computer science, "vague" usually seems to be given the same meaning it carries in [linguistics and philosophy][vagueness] - namely, some predicate is *vague* when it is not clear in all cases whether it's satisfied or not. Thus, it's not exactly the same thing as "not precise".

[vagueness]: https://en.wikipedia.org/wiki/Vagueness

When discussing exceptions, I think that "overly broad" is perhaps more what you're after. "Vague" seems to imply that there can be uncertainty as to the fact of whether (in some particular case) an exception was thrown or not – which I don't think is true in any programming language! "Overly broad", by contrast, just means that we've made a poor choice of type (or class, for OO languages) for the exception - semantically, it could cover a multitude of sorts of situation, and it will not be clear to a caller which of them was the case.

**Comment by jappeace** [comment]
Thank you!

I appreciate this, you clearly put a lot of effort into this review.
I'll go trough your suggestions tonight.

**Comment by phlummox** [comment]
Quite alright - before programming, my first job was doing proofreading, so it takes very little time.

**Comment by jappeace** [comment]
These changes were already applied
